"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class UserAddOptions(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NO_PASSWORD_FIELD_NUMBER: builtins.int
    no_password: builtins.bool = ...

    def __init__(self,
        *,
        no_password : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"no_password",b"no_password"]) -> None: ...
global___UserAddOptions = UserAddOptions

class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    ROLES_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    name: builtins.bytes = ...
    password: builtins.bytes = ...
    roles: google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text] = ...

    @property
    def options(self) -> global___UserAddOptions: ...

    def __init__(self,
        *,
        name : builtins.bytes = ...,
        password : builtins.bytes = ...,
        roles : typing.Optional[typing.Iterable[typing.Text]] = ...,
        options : typing.Optional[global___UserAddOptions] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"options",b"options"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"options",b"options",u"password",b"password",u"roles",b"roles"]) -> None: ...
global___User = User

class Permission(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Type.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        READ = Permission.Type.V(0)
        WRITE = Permission.Type.V(1)
        READWRITE = Permission.Type.V(2)
    class Type(metaclass=_Type):
        V = typing.NewType('V', builtins.int)
    READ = Permission.Type.V(0)
    WRITE = Permission.Type.V(1)
    READWRITE = Permission.Type.V(2)

    PERMTYPE_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    RANGE_END_FIELD_NUMBER: builtins.int
    permType: global___Permission.Type.V = ...
    key: builtins.bytes = ...
    range_end: builtins.bytes = ...

    def __init__(self,
        *,
        permType : global___Permission.Type.V = ...,
        key : builtins.bytes = ...,
        range_end : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key",u"permType",b"permType",u"range_end",b"range_end"]) -> None: ...
global___Permission = Permission

class Role(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    KEYPERMISSION_FIELD_NUMBER: builtins.int
    name: builtins.bytes = ...

    @property
    def keyPermission(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Permission]: ...

    def __init__(self,
        *,
        name : builtins.bytes = ...,
        keyPermission : typing.Optional[typing.Iterable[global___Permission]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"keyPermission",b"keyPermission",u"name",b"name"]) -> None: ...
global___Role = Role
