"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class KeyValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KEY_FIELD_NUMBER: builtins.int
    CREATE_REVISION_FIELD_NUMBER: builtins.int
    MOD_REVISION_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    LEASE_FIELD_NUMBER: builtins.int
    key: builtins.bytes = ...
    create_revision: builtins.int = ...
    mod_revision: builtins.int = ...
    version: builtins.int = ...
    value: builtins.bytes = ...
    lease: builtins.int = ...

    def __init__(self,
        *,
        key : builtins.bytes = ...,
        create_revision : builtins.int = ...,
        mod_revision : builtins.int = ...,
        version : builtins.int = ...,
        value : builtins.bytes = ...,
        lease : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"create_revision",b"create_revision",u"key",b"key",u"lease",b"lease",u"mod_revision",b"mod_revision",u"value",b"value",u"version",b"version"]) -> None: ...
global___KeyValue = KeyValue

class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _EventType(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EventType.V], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        PUT = Event.EventType.V(0)
        DELETE = Event.EventType.V(1)
    class EventType(metaclass=_EventType):
        V = typing.NewType('V', builtins.int)
    PUT = Event.EventType.V(0)
    DELETE = Event.EventType.V(1)

    TYPE_FIELD_NUMBER: builtins.int
    KV_FIELD_NUMBER: builtins.int
    PREV_KV_FIELD_NUMBER: builtins.int
    type: global___Event.EventType.V = ...

    @property
    def kv(self) -> global___KeyValue: ...

    @property
    def prev_kv(self) -> global___KeyValue: ...

    def __init__(self,
        *,
        type : global___Event.EventType.V = ...,
        kv : typing.Optional[global___KeyValue] = ...,
        prev_kv : typing.Optional[global___KeyValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"kv",b"kv",u"prev_kv",b"prev_kv"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"kv",b"kv",u"prev_kv",b"prev_kv",u"type",b"type"]) -> None: ...
global___Event = Event
