# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lease.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import rpc_pb2 as rpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lease.proto',
  package='leasepb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0blease.proto\x12\x07leasepb\x1a\trpc.proto\"6\n\x05Lease\x12\n\n\x02ID\x18\x01 \x01(\x03\x12\x0b\n\x03TTL\x18\x02 \x01(\x03\x12\x14\n\x0cRemainingTTL\x18\x03 \x01(\x03\"\\\n\x14LeaseInternalRequest\x12\x44\n\x16LeaseTimeToLiveRequest\x18\x01 \x01(\x0b\x32$.etcdserverpb.LeaseTimeToLiveRequest\"_\n\x15LeaseInternalResponse\x12\x46\n\x17LeaseTimeToLiveResponse\x18\x01 \x01(\x0b\x32%.etcdserverpb.LeaseTimeToLiveResponseb\x06proto3'
  ,
  dependencies=[rpc__pb2.DESCRIPTOR,])




_LEASE = _descriptor.Descriptor(
  name='Lease',
  full_name='leasepb.Lease',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='leasepb.Lease.ID', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TTL', full_name='leasepb.Lease.TTL', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RemainingTTL', full_name='leasepb.Lease.RemainingTTL', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=89,
)


_LEASEINTERNALREQUEST = _descriptor.Descriptor(
  name='LeaseInternalRequest',
  full_name='leasepb.LeaseInternalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='LeaseTimeToLiveRequest', full_name='leasepb.LeaseInternalRequest.LeaseTimeToLiveRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=183,
)


_LEASEINTERNALRESPONSE = _descriptor.Descriptor(
  name='LeaseInternalResponse',
  full_name='leasepb.LeaseInternalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='LeaseTimeToLiveResponse', full_name='leasepb.LeaseInternalResponse.LeaseTimeToLiveResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=280,
)

_LEASEINTERNALREQUEST.fields_by_name['LeaseTimeToLiveRequest'].message_type = rpc__pb2._LEASETIMETOLIVEREQUEST
_LEASEINTERNALRESPONSE.fields_by_name['LeaseTimeToLiveResponse'].message_type = rpc__pb2._LEASETIMETOLIVERESPONSE
DESCRIPTOR.message_types_by_name['Lease'] = _LEASE
DESCRIPTOR.message_types_by_name['LeaseInternalRequest'] = _LEASEINTERNALREQUEST
DESCRIPTOR.message_types_by_name['LeaseInternalResponse'] = _LEASEINTERNALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lease = _reflection.GeneratedProtocolMessageType('Lease', (_message.Message,), {
  'DESCRIPTOR' : _LEASE,
  '__module__' : 'lease_pb2'
  # @@protoc_insertion_point(class_scope:leasepb.Lease)
  })
_sym_db.RegisterMessage(Lease)

LeaseInternalRequest = _reflection.GeneratedProtocolMessageType('LeaseInternalRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEASEINTERNALREQUEST,
  '__module__' : 'lease_pb2'
  # @@protoc_insertion_point(class_scope:leasepb.LeaseInternalRequest)
  })
_sym_db.RegisterMessage(LeaseInternalRequest)

LeaseInternalResponse = _reflection.GeneratedProtocolMessageType('LeaseInternalResponse', (_message.Message,), {
  'DESCRIPTOR' : _LEASEINTERNALRESPONSE,
  '__module__' : 'lease_pb2'
  # @@protoc_insertion_point(class_scope:leasepb.LeaseInternalResponse)
  })
_sym_db.RegisterMessage(LeaseInternalResponse)


# @@protoc_insertion_point(module_scope)
