"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import rpc_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class Lease(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    TTL_FIELD_NUMBER: builtins.int
    REMAININGTTL_FIELD_NUMBER: builtins.int
    ID: builtins.int = ...
    TTL: builtins.int = ...
    RemainingTTL: builtins.int = ...

    def __init__(self,
        *,
        ID : builtins.int = ...,
        TTL : builtins.int = ...,
        RemainingTTL : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ID",b"ID",u"RemainingTTL",b"RemainingTTL",u"TTL",b"TTL"]) -> None: ...
global___Lease = Lease

class LeaseInternalRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LEASETIMETOLIVEREQUEST_FIELD_NUMBER: builtins.int

    @property
    def LeaseTimeToLiveRequest(self) -> rpc_pb2.LeaseTimeToLiveRequest: ...

    def __init__(self,
        *,
        LeaseTimeToLiveRequest : typing.Optional[rpc_pb2.LeaseTimeToLiveRequest] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"LeaseTimeToLiveRequest",b"LeaseTimeToLiveRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"LeaseTimeToLiveRequest",b"LeaseTimeToLiveRequest"]) -> None: ...
global___LeaseInternalRequest = LeaseInternalRequest

class LeaseInternalResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    LEASETIMETOLIVERESPONSE_FIELD_NUMBER: builtins.int

    @property
    def LeaseTimeToLiveResponse(self) -> rpc_pb2.LeaseTimeToLiveResponse: ...

    def __init__(self,
        *,
        LeaseTimeToLiveResponse : typing.Optional[rpc_pb2.LeaseTimeToLiveResponse] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"LeaseTimeToLiveResponse",b"LeaseTimeToLiveResponse"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"LeaseTimeToLiveResponse",b"LeaseTimeToLiveResponse"]) -> None: ...
global___LeaseInternalResponse = LeaseInternalResponse
