"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import etcdserver_pb2
import google.protobuf.descriptor
import google.protobuf.message
import rpc_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class RequestHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    AUTH_REVISION_FIELD_NUMBER: builtins.int
    ID: builtins.int = ...
    username: typing.Text = ...
    auth_revision: builtins.int = ...

    def __init__(self,
        *,
        ID : builtins.int = ...,
        username : typing.Text = ...,
        auth_revision : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ID",b"ID",u"auth_revision",b"auth_revision",u"username",b"username"]) -> None: ...
global___RequestHeader = RequestHeader

class InternalRaftRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HEADER_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    V2_FIELD_NUMBER: builtins.int
    RANGE_FIELD_NUMBER: builtins.int
    PUT_FIELD_NUMBER: builtins.int
    DELETE_RANGE_FIELD_NUMBER: builtins.int
    TXN_FIELD_NUMBER: builtins.int
    COMPACTION_FIELD_NUMBER: builtins.int
    LEASE_GRANT_FIELD_NUMBER: builtins.int
    LEASE_REVOKE_FIELD_NUMBER: builtins.int
    ALARM_FIELD_NUMBER: builtins.int
    LEASE_CHECKPOINT_FIELD_NUMBER: builtins.int
    AUTH_ENABLE_FIELD_NUMBER: builtins.int
    AUTH_DISABLE_FIELD_NUMBER: builtins.int
    AUTHENTICATE_FIELD_NUMBER: builtins.int
    AUTH_USER_ADD_FIELD_NUMBER: builtins.int
    AUTH_USER_DELETE_FIELD_NUMBER: builtins.int
    AUTH_USER_GET_FIELD_NUMBER: builtins.int
    AUTH_USER_CHANGE_PASSWORD_FIELD_NUMBER: builtins.int
    AUTH_USER_GRANT_ROLE_FIELD_NUMBER: builtins.int
    AUTH_USER_REVOKE_ROLE_FIELD_NUMBER: builtins.int
    AUTH_USER_LIST_FIELD_NUMBER: builtins.int
    AUTH_ROLE_LIST_FIELD_NUMBER: builtins.int
    AUTH_ROLE_ADD_FIELD_NUMBER: builtins.int
    AUTH_ROLE_DELETE_FIELD_NUMBER: builtins.int
    AUTH_ROLE_GET_FIELD_NUMBER: builtins.int
    AUTH_ROLE_GRANT_PERMISSION_FIELD_NUMBER: builtins.int
    AUTH_ROLE_REVOKE_PERMISSION_FIELD_NUMBER: builtins.int
    ID: builtins.int = ...

    @property
    def header(self) -> global___RequestHeader: ...

    @property
    def v2(self) -> etcdserver_pb2.Request: ...

    @property
    def range(self) -> rpc_pb2.RangeRequest: ...

    @property
    def put(self) -> rpc_pb2.PutRequest: ...

    @property
    def delete_range(self) -> rpc_pb2.DeleteRangeRequest: ...

    @property
    def txn(self) -> rpc_pb2.TxnRequest: ...

    @property
    def compaction(self) -> rpc_pb2.CompactionRequest: ...

    @property
    def lease_grant(self) -> rpc_pb2.LeaseGrantRequest: ...

    @property
    def lease_revoke(self) -> rpc_pb2.LeaseRevokeRequest: ...

    @property
    def alarm(self) -> rpc_pb2.AlarmRequest: ...

    @property
    def lease_checkpoint(self) -> rpc_pb2.LeaseCheckpointRequest: ...

    @property
    def auth_enable(self) -> rpc_pb2.AuthEnableRequest: ...

    @property
    def auth_disable(self) -> rpc_pb2.AuthDisableRequest: ...

    @property
    def authenticate(self) -> global___InternalAuthenticateRequest: ...

    @property
    def auth_user_add(self) -> rpc_pb2.AuthUserAddRequest: ...

    @property
    def auth_user_delete(self) -> rpc_pb2.AuthUserDeleteRequest: ...

    @property
    def auth_user_get(self) -> rpc_pb2.AuthUserGetRequest: ...

    @property
    def auth_user_change_password(self) -> rpc_pb2.AuthUserChangePasswordRequest: ...

    @property
    def auth_user_grant_role(self) -> rpc_pb2.AuthUserGrantRoleRequest: ...

    @property
    def auth_user_revoke_role(self) -> rpc_pb2.AuthUserRevokeRoleRequest: ...

    @property
    def auth_user_list(self) -> rpc_pb2.AuthUserListRequest: ...

    @property
    def auth_role_list(self) -> rpc_pb2.AuthRoleListRequest: ...

    @property
    def auth_role_add(self) -> rpc_pb2.AuthRoleAddRequest: ...

    @property
    def auth_role_delete(self) -> rpc_pb2.AuthRoleDeleteRequest: ...

    @property
    def auth_role_get(self) -> rpc_pb2.AuthRoleGetRequest: ...

    @property
    def auth_role_grant_permission(self) -> rpc_pb2.AuthRoleGrantPermissionRequest: ...

    @property
    def auth_role_revoke_permission(self) -> rpc_pb2.AuthRoleRevokePermissionRequest: ...

    def __init__(self,
        *,
        header : typing.Optional[global___RequestHeader] = ...,
        ID : builtins.int = ...,
        v2 : typing.Optional[etcdserver_pb2.Request] = ...,
        range : typing.Optional[rpc_pb2.RangeRequest] = ...,
        put : typing.Optional[rpc_pb2.PutRequest] = ...,
        delete_range : typing.Optional[rpc_pb2.DeleteRangeRequest] = ...,
        txn : typing.Optional[rpc_pb2.TxnRequest] = ...,
        compaction : typing.Optional[rpc_pb2.CompactionRequest] = ...,
        lease_grant : typing.Optional[rpc_pb2.LeaseGrantRequest] = ...,
        lease_revoke : typing.Optional[rpc_pb2.LeaseRevokeRequest] = ...,
        alarm : typing.Optional[rpc_pb2.AlarmRequest] = ...,
        lease_checkpoint : typing.Optional[rpc_pb2.LeaseCheckpointRequest] = ...,
        auth_enable : typing.Optional[rpc_pb2.AuthEnableRequest] = ...,
        auth_disable : typing.Optional[rpc_pb2.AuthDisableRequest] = ...,
        authenticate : typing.Optional[global___InternalAuthenticateRequest] = ...,
        auth_user_add : typing.Optional[rpc_pb2.AuthUserAddRequest] = ...,
        auth_user_delete : typing.Optional[rpc_pb2.AuthUserDeleteRequest] = ...,
        auth_user_get : typing.Optional[rpc_pb2.AuthUserGetRequest] = ...,
        auth_user_change_password : typing.Optional[rpc_pb2.AuthUserChangePasswordRequest] = ...,
        auth_user_grant_role : typing.Optional[rpc_pb2.AuthUserGrantRoleRequest] = ...,
        auth_user_revoke_role : typing.Optional[rpc_pb2.AuthUserRevokeRoleRequest] = ...,
        auth_user_list : typing.Optional[rpc_pb2.AuthUserListRequest] = ...,
        auth_role_list : typing.Optional[rpc_pb2.AuthRoleListRequest] = ...,
        auth_role_add : typing.Optional[rpc_pb2.AuthRoleAddRequest] = ...,
        auth_role_delete : typing.Optional[rpc_pb2.AuthRoleDeleteRequest] = ...,
        auth_role_get : typing.Optional[rpc_pb2.AuthRoleGetRequest] = ...,
        auth_role_grant_permission : typing.Optional[rpc_pb2.AuthRoleGrantPermissionRequest] = ...,
        auth_role_revoke_permission : typing.Optional[rpc_pb2.AuthRoleRevokePermissionRequest] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"alarm",b"alarm",u"auth_disable",b"auth_disable",u"auth_enable",b"auth_enable",u"auth_role_add",b"auth_role_add",u"auth_role_delete",b"auth_role_delete",u"auth_role_get",b"auth_role_get",u"auth_role_grant_permission",b"auth_role_grant_permission",u"auth_role_list",b"auth_role_list",u"auth_role_revoke_permission",b"auth_role_revoke_permission",u"auth_user_add",b"auth_user_add",u"auth_user_change_password",b"auth_user_change_password",u"auth_user_delete",b"auth_user_delete",u"auth_user_get",b"auth_user_get",u"auth_user_grant_role",b"auth_user_grant_role",u"auth_user_list",b"auth_user_list",u"auth_user_revoke_role",b"auth_user_revoke_role",u"authenticate",b"authenticate",u"compaction",b"compaction",u"delete_range",b"delete_range",u"header",b"header",u"lease_checkpoint",b"lease_checkpoint",u"lease_grant",b"lease_grant",u"lease_revoke",b"lease_revoke",u"put",b"put",u"range",b"range",u"txn",b"txn",u"v2",b"v2"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"ID",b"ID",u"alarm",b"alarm",u"auth_disable",b"auth_disable",u"auth_enable",b"auth_enable",u"auth_role_add",b"auth_role_add",u"auth_role_delete",b"auth_role_delete",u"auth_role_get",b"auth_role_get",u"auth_role_grant_permission",b"auth_role_grant_permission",u"auth_role_list",b"auth_role_list",u"auth_role_revoke_permission",b"auth_role_revoke_permission",u"auth_user_add",b"auth_user_add",u"auth_user_change_password",b"auth_user_change_password",u"auth_user_delete",b"auth_user_delete",u"auth_user_get",b"auth_user_get",u"auth_user_grant_role",b"auth_user_grant_role",u"auth_user_list",b"auth_user_list",u"auth_user_revoke_role",b"auth_user_revoke_role",u"authenticate",b"authenticate",u"compaction",b"compaction",u"delete_range",b"delete_range",u"header",b"header",u"lease_checkpoint",b"lease_checkpoint",u"lease_grant",b"lease_grant",u"lease_revoke",b"lease_revoke",u"put",b"put",u"range",b"range",u"txn",b"txn",u"v2",b"v2"]) -> None: ...
global___InternalRaftRequest = InternalRaftRequest

class EmptyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___EmptyResponse = EmptyResponse

class InternalAuthenticateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    SIMPLE_TOKEN_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    password: typing.Text = ...
    simple_token: typing.Text = ...

    def __init__(self,
        *,
        name : typing.Text = ...,
        password : typing.Text = ...,
        simple_token : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"name",b"name",u"password",b"password",u"simple_token",b"simple_token"]) -> None: ...
global___InternalAuthenticateRequest = InternalAuthenticateRequest
