# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snap.proto

import sys

_b = (
    sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
)
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="snap.proto",
    package="snappb",
    syntax="proto2",
    serialized_options=None,
    serialized_pb=_b(
        '\n\nsnap.proto\x12\x06snappb"%\n\x08snapshot\x12\x0b\n\x03\x63rc\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c'
    ),
)


_SNAPSHOT = _descriptor.Descriptor(
    name="snapshot",
    full_name="snappb.snapshot",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="crc",
            full_name="snappb.snapshot.crc",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="data",
            full_name="snappb.snapshot.data",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=22,
    serialized_end=59,
)

DESCRIPTOR.message_types_by_name["snapshot"] = _SNAPSHOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

snapshot = _reflection.GeneratedProtocolMessageType(
    "snapshot",
    (_message.Message,),
    {
        "DESCRIPTOR": _SNAPSHOT,
        "__module__": "snap_pb2"
        # @@protoc_insertion_point(class_scope:snappb.snapshot)
    },
)
_sym_db.RegisterMessage(snapshot)


# @@protoc_insertion_point(module_scope)
