"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class snapshot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CRC_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    crc: builtins.int = ...
    data: builtins.bytes = ...

    def __init__(self,
        *,
        crc : typing.Optional[builtins.int] = ...,
        data : typing.Optional[builtins.bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"crc",b"crc",u"data",b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"crc",b"crc",u"data",b"data"]) -> None: ...
global___snapshot = snapshot
