"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import rpc_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class LockRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    NAME_FIELD_NUMBER: builtins.int
    LEASE_FIELD_NUMBER: builtins.int
    name: builtins.bytes = ...
    lease: builtins.int = ...

    def __init__(self,
        *,
        name : builtins.bytes = ...,
        lease : builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"lease",b"lease",u"name",b"name"]) -> None: ...
global___LockRequest = LockRequest

class LockResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HEADER_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    key: builtins.bytes = ...

    @property
    def header(self) -> rpc_pb2.ResponseHeader: ...

    def __init__(self,
        *,
        header : typing.Optional[rpc_pb2.ResponseHeader] = ...,
        key : builtins.bytes = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"header",b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"header",b"header",u"key",b"key"]) -> None: ...
global___LockResponse = LockResponse

class UnlockRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    KEY_FIELD_NUMBER: builtins.int
    key: builtins.bytes = ...

    def __init__(self,
        *,
        key : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"key",b"key"]) -> None: ...
global___UnlockRequest = UnlockRequest

class UnlockResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HEADER_FIELD_NUMBER: builtins.int

    @property
    def header(self) -> rpc_pb2.ResponseHeader: ...

    def __init__(self,
        *,
        header : typing.Optional[rpc_pb2.ResponseHeader] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"header",b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"header",b"header"]) -> None: ...
global___UnlockResponse = UnlockResponse
