# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3lock.proto

import sys

_b = (
    sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
)
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import rpc_pb2 as rpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="v3lock.proto",
    package="v3lockpb",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x0cv3lock.proto\x12\x08v3lockpb\x1a\trpc.proto"*\n\x0bLockRequest\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\r\n\x05lease\x18\x02 \x01(\x03"I\n\x0cLockResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.etcdserverpb.ResponseHeader\x12\x0b\n\x03key\x18\x02 \x01(\x0c"\x1c\n\rUnlockRequest\x12\x0b\n\x03key\x18\x01 \x01(\x0c">\n\x0eUnlockResponse\x12,\n\x06header\x18\x01 \x01(\x0b\x32\x1c.etcdserverpb.ResponseHeader2~\n\x04Lock\x12\x37\n\x04Lock\x12\x15.v3lockpb.LockRequest\x1a\x16.v3lockpb.LockResponse"\x00\x12=\n\x06Unlock\x12\x17.v3lockpb.UnlockRequest\x1a\x18.v3lockpb.UnlockResponse"\x00\x62\x06proto3'
    ),
    dependencies=[rpc__pb2.DESCRIPTOR,],
)


_LOCKREQUEST = _descriptor.Descriptor(
    name="LockRequest",
    full_name="v3lockpb.LockRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="v3lockpb.LockRequest.name",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="lease",
            full_name="v3lockpb.LockRequest.lease",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=37,
    serialized_end=79,
)


_LOCKRESPONSE = _descriptor.Descriptor(
    name="LockResponse",
    full_name="v3lockpb.LockResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="header",
            full_name="v3lockpb.LockResponse.header",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="key",
            full_name="v3lockpb.LockResponse.key",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=81,
    serialized_end=154,
)


_UNLOCKREQUEST = _descriptor.Descriptor(
    name="UnlockRequest",
    full_name="v3lockpb.UnlockRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="v3lockpb.UnlockRequest.key",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=156,
    serialized_end=184,
)


_UNLOCKRESPONSE = _descriptor.Descriptor(
    name="UnlockResponse",
    full_name="v3lockpb.UnlockResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="header",
            full_name="v3lockpb.UnlockResponse.header",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=186,
    serialized_end=248,
)

_LOCKRESPONSE.fields_by_name["header"].message_type = rpc__pb2._RESPONSEHEADER
_UNLOCKRESPONSE.fields_by_name[
    "header"
].message_type = rpc__pb2._RESPONSEHEADER
DESCRIPTOR.message_types_by_name["LockRequest"] = _LOCKREQUEST
DESCRIPTOR.message_types_by_name["LockResponse"] = _LOCKRESPONSE
DESCRIPTOR.message_types_by_name["UnlockRequest"] = _UNLOCKREQUEST
DESCRIPTOR.message_types_by_name["UnlockResponse"] = _UNLOCKRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LockRequest = _reflection.GeneratedProtocolMessageType(
    "LockRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOCKREQUEST,
        "__module__": "v3lock_pb2"
        # @@protoc_insertion_point(class_scope:v3lockpb.LockRequest)
    },
)
_sym_db.RegisterMessage(LockRequest)

LockResponse = _reflection.GeneratedProtocolMessageType(
    "LockResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOCKRESPONSE,
        "__module__": "v3lock_pb2"
        # @@protoc_insertion_point(class_scope:v3lockpb.LockResponse)
    },
)
_sym_db.RegisterMessage(LockResponse)

UnlockRequest = _reflection.GeneratedProtocolMessageType(
    "UnlockRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _UNLOCKREQUEST,
        "__module__": "v3lock_pb2"
        # @@protoc_insertion_point(class_scope:v3lockpb.UnlockRequest)
    },
)
_sym_db.RegisterMessage(UnlockRequest)

UnlockResponse = _reflection.GeneratedProtocolMessageType(
    "UnlockResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _UNLOCKRESPONSE,
        "__module__": "v3lock_pb2"
        # @@protoc_insertion_point(class_scope:v3lockpb.UnlockResponse)
    },
)
_sym_db.RegisterMessage(UnlockResponse)


_LOCK = _descriptor.ServiceDescriptor(
    name="Lock",
    full_name="v3lockpb.Lock",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=250,
    serialized_end=376,
    methods=[
        _descriptor.MethodDescriptor(
            name="Lock",
            full_name="v3lockpb.Lock.Lock",
            index=0,
            containing_service=None,
            input_type=_LOCKREQUEST,
            output_type=_LOCKRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="Unlock",
            full_name="v3lockpb.Lock.Unlock",
            index=1,
            containing_service=None,
            input_type=_UNLOCKREQUEST,
            output_type=_UNLOCKRESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_LOCK)

DESCRIPTOR.services_by_name["Lock"] = _LOCK

# @@protoc_insertion_point(module_scope)
